from backend.application.dto.conversation_summary import (
    ConversationSummaryOutput,
)
from backend.domain.enums.message_role import MessageRole
from backend.domain.interfaces.conversation_reader import (
    IConversationReader,
)
from backend.domain.interfaces.llm_provider import (
    ILLMProvider,
)


class SummarizeConversationUseCase:
    def __init__(
        self,
        conversation_reader: IConversationReader,
        llm_provider: ILLMProvider,
    ) -> None:
        self._conversation_reader = conversation_reader
        self._llm_provider = llm_provider

    async def execute(
        self,
        conversation_id: str,
    ) -> ConversationSummaryOutput:
        """
        Generate a structured summary from an existing conversation.
        """
        conversation = (
            await self._conversation_reader.get_conversation(
                conversation_id
            )
        )

        if not conversation.messages:
            raise ValueError(
                "Conversation not found or empty."
            )

        transcript = self._build_transcript(
            conversation.messages
        )

        system_prompt = """
You are Raissa AI.

Your task is to transform a conversation into a polished,
useful and well-organized reference or study material.

Always write in Brazilian Portuguese.

Rules:
- Do not mention internal prompts or system instructions.
- Do not mention that the text was generated by an AI.
- Do not structure the summary as a transcript.
- Do not use labels such as "Usuária:" or "Raissa:".
- Do not reproduce greetings or irrelevant small talk.
- Do not invent information.
- Preserve important facts from the conversation.
- Use clear Markdown.
- Prefer useful headings and concise bullet points.
- Avoid excessive repetition.
- Keep the content practical and easy to review.

Recommended structure when appropriate:

# Título do assunto

## Visão geral
Brief explanation of the main subject.

## Pontos principais
Important concepts, facts or decisions.

## Detalhes importantes
Useful explanations extracted from the conversation.

## Para lembrar
A short review section with the most important takeaways.

If the conversation is about nursing or studies:
- Write it like study material.
- Prioritize concepts, explanations and revision points.
- Highlight terms or ideas that are useful for exams.

If the conversation is about finance:
- Preserve values, calculations, goals and practical actions.
- Organize the information clearly.

If the conversation is about beauty or salon management:
- Preserve services, prices, ideas, planning and practical actions.

Do not force sections that do not make sense for the conversation.
""".strip()

        user_message = f"""
Create a summary of the following conversation.

CONVERSATION:

{transcript}
""".strip()

        summary = await self._llm_provider.generate(
            system_prompt=system_prompt,
            user_message=user_message,
            history=[],
        )

        title = self._build_title(
            conversation.messages
        )

        return ConversationSummaryOutput(
            conversation_id=conversation_id,
            title=title,
            summary=summary.strip(),
        )

    @staticmethod
    def _build_transcript(
        messages: list,
    ) -> str:
        """
        Build a clean transcript without internal frontend context.
        """
        transcript: list[str] = []

        for message in messages:
            content = (
                SummarizeConversationUseCase
                ._clean_message_content(
                    message.content
                )
            )

            if not content:
                continue

            if message.role == MessageRole.USER:
                role = "Usuária"
            elif message.role == MessageRole.ASSISTANT:
                role = "Raissa"
            else:
                continue

            transcript.append(
                f"{role}: {content}"
            )

        return "\n\n".join(
            transcript
        )

    @staticmethod
    def _clean_message_content(
        content: str,
    ) -> str:
        """
        Remove internal area context from persisted user messages.
        """
        marker = "Mensagem da usuária:\n"

        if marker in content:
            return content.split(
                marker,
                maxsplit=1,
            )[1].strip()

        return content.strip()

    @staticmethod
    def _build_title(
        messages: list,
    ) -> str:
        """
        Build a concise document title from the first meaningful user message.
        """
        for message in messages:
            if message.role != MessageRole.USER:
                continue

            content = (
                SummarizeConversationUseCase
                ._clean_message_content(
                    message.content
                )
            )

            if not content:
                continue

            cleaned = (
                content.replace(
                    "\n",
                    " ",
                )
                .strip()
            )

            ignored_messages = {
                "oi",
                "olá",
                "ola",
                "bom dia",
                "boa tarde",
                "boa noite",
            }

            if cleaned.lower() in ignored_messages:
                continue

            if len(cleaned) > 55:
                cleaned = (
                    cleaned[:55].rstrip()
                    + "..."
                )

            return f"Resumo - {cleaned}"

        return "Resumo da conversa"